name: 💡 Feature request
description: Suggest a feature or enhancement for Pandaroll
title: "[FR] <title>"
labels: [Feature Request]
body:
- type: checkboxes
  attributes:
    label: Is there an existing feature request for this?
    description: Please search to see if an feature request already exists.
    options:
    - label: I have searched the existing feature requests.
      required: true
- type: textarea
  attributes:
    label: Describe the feature you'd like
    description: A clear description of the feature. What problem does it solve for you?
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false